---
title: "Isaac Hale's Public Scholarship"
---

<head>
<title>Isaac Hale's Public Scholarship</title>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-140699540-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-140699540-1');
</script>
</head>

<font size="+3"><b>Public Scholarship</b></font>


Public scholarship improves academic research, generates public interest in our work, and communicates the substantive importance of our research to policymakers and voters. In my current position at Occidental College I have contributed to initiatives to enact electoral reform in the US and Canada. In my previous position at the UCSB Blum Center, I was part of an interdisciplinary team of academics, researchers, and community organizations from across California who have recently released <a href = "https://centralcoastequity.org/regional-equity-study/"><i> Towards a Just and Equitable Central Coast</i></a> which is a report on racial, gender, immigration, and economic inequality in the state’s Central Coast region. In this capacity I also led and participated in several online policy workshops on the California housing crisis. 

I have had the privilege to share my research and expertise with a variety of public-facing media outlets. My research has been featured in <i>The New York Times</i>, <i>The Sacramento Bee</i>,  <i>The Texas Tribune</i>, <i>SF Gate</i>, <i>Roll Call</i>, <i>Salon</i>, <i>La Tercera</i>, <i>Pacific Standard</i>, <i>Democratic Audit</i>, <i>RAISE the Vote</i>, <i>LSE Latin America and Caribbean Centre</i>, and <i>The California Aggie</i>. I have been interviewed on TV stations such as <i>ABC 10</i>, <i>FOX 40</i>, <i>KCRA 3</i>, and <i>CBS 13</i> television news to discuss state and national politics as a political scientists. These interviews (and more) can be found on my <a href="https://www.youtube.com/@ProfessorIsaacHale">YouTube channel</a>. In addition, I have appeared on radio stations like <i>93.1 KFBK</i> and <i> KQED </i> as well as podcasts like <i>Communication Matters</i> to discuss my research and current events. 
<br><br>



# Policy Reports

<ol>

 <li> <a href="http://centralcoastequity.org/regional-equity-study/">Towards a Just and Equitable Central Coast</a> - a report by the <i><a href="https://www.blumcenter.ucsb.edu">UCSB Blum Center</a></i>, the <i><a href="https://dornsife.usc.edu/eri">USC Equity Research Institute</a></i>, and <i><a href="https://fundforsantabarbara.org/">The Fund for Santa Barbara</a></i> (2021)


</ol>
<br>

# Invited Blog Posts & Op-eds

<ol>

 <li> <a href="https://blogs.lse.ac.uk/usappblog/2022/10/31/for-many-2020-presidential-election-voters-economic-concerns-about-covid-19-restrictions-trumped-public-health/">For many 2020 presidential election voters, economic concerns about COVID-19 restrictions trumped public health</a> - <i>LSE USAPP</i> blog post (2022)

 <li> <a href="https://blogs.lse.ac.uk/latamcaribbean/2021/11/17/chile-could-be-a-mirror-to-future-political-reforms-in-the-world/">Chile could be a mirror to future political reforms in the world</a> - <i>LSE Latin
America and Caribbean Centre</i> blog post (2021)
  <ul>
  <li> <a href="https://blogs.lse.ac.uk/latamcaribbean/2021/11/17/chile-puede-ser-un-espejo-para-futuras-reformas-politicas-en-el-mundo/"> Versión en español </a></li>
<p class="half-line">&nbsp;</p>
  </ul>

 <li> <a href="https://connect.apsanet.org/raisethevote/2020/07/22/will-trump-congressional-republicans-benefit-from-white-racial-attitudes-in-2020/">Will Trump & Congressional Republicans Benefit from White Racial Attitudes in 2020?</a> - <i>RAISE the Vote</i> APSA blog post (2020)

<li> <a href="https://tinyurl.com/yxluq74p">Strategic voting in the 2015 general election: why Liberal Democrats didn’t vote for their own party</a> - <i>Democratic Audit</i> blog post (2019)

<li> <a href="https://www.huffingtonpost.com/isaac-hale/torture-and-the-rule-of-l_b_814272.html">Torture and the Rule of Law</a> - <i>The Huffington Post</i> op-ed (2011)
</ol>
<br>

# Policy Workshops

<ol>

<li> <a href="https://youtu.be/M6P1UN5MKCc">ACT On Homelessness All-Call Meeting </a> - <i>Santa Barbara Alliance for Community Transformation</i> (2022)

<li> <a href="https://youtu.be/yCxKMDU0TRs">The UCSB Housing Crisis </a> - <i>UC Santa Barbara Blum Center</i> (2022)

<li> <a href="https://youtu.be/KILr3LcQ0F0">The Housing Crisis in California & the Central Coast </a> - <i>UC Santa Barbara Blum Center</i> (2022)

</ol>

<br>

# Media Coverage of My Research

<ol>

<li> <a href="https://magazine.ucdavis.edu/do-attitudes-about-race-affect-vote-choice/">Do Attitudes About Race Affect Vote Choice?</a> - <i>UC Davis Magazine</i> (2020)

<li> <a href=https://nyti.ms/3jWSW5b">Biden Is Not Out of the Woods</a> - <i>The New York Times</i> (2020)

 <li> <a href="https://tinyurl.com/yyc32ssr">Au sein du  parti rèpublicain, des anti-Trump bien silencieux</a> - <i>La Croix</i> (2019)
 
 <li> <a href="https://tinyurl.com/y3ksxsjn">Duncan Hunter said person making ‘OK’ sign in photo was a ‘stranger.’ The man calls Hunter a friend</a> - <i>Roll Call</i> (2019)
 
 <li> <a href="https://tinyurl.com/y3ssqw3y">Trump’s strategy of racial resentment won’t work in California, researcher says</a> - <i>The Sacramento Bee</i> (2019)
 
 <li> <a href="https://tinyurl.com/y5vrkrxb">White racial resentment is a winning Republican strategy, this political scientist says</a> - <i>The Sacramento Bee</i> (2019)
 
 <li> <a href="https://tinyurl.com/y5yz9wem">Trump's racist tweets are part of a coordinated 2020 strategy</a> - <i>Salon</i> (2019)
 
 <li> <a href="https://tinyurl.com/y5y2de8e">Ataques racistas de Trump a congresistas definen tono  de su campaña presidencial</a> - <i>La Tercera</i> (2019)
 
 <li> <a href="https://nyti.ms/2XUY7Xg">Trump Sets the 2020 Tone: Like 2016, Only This Time ‘the Squad’ Is Here</a> - <i>The New York Times</i> (2019)
 
 <li> <a href="https://tinyurl.com/yynrxtlc">Trump's Racist Remarks Helped Boost Down-Ballot Republicans in 2016</a> - <i>Pacific Standard</i> (2019)
 
<li> <a href="https://nyti.ms/2IOsZqq">The Deepening ‘Racialization’ of American Politics</a> - <i>The New York Times</i> (2019)
 
</ol>
<br>


# Television Interviews

You may find video of my television interviews on my <a href="https://www.youtube.com/@ProfessorIsaacHale">YouTube channel</a>. A YouTube playlist with my television interviews is also embedded below. In addition, each appearance is listed below, with a link to the news outlet's writeup of the segment (if available).

<br>

<p align="center">
<iframe width="640" height="360" src="https://www.youtube.com/embed/videoseries?list=PLc6o2XJt0uxC1WA4juKe5xcD0H5uLZQFw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>
</p>

<br>


<ol>

<li> <a href="https://youtu.be/8HjJumneEKE?si=DkBnUjfeW0IcfyPR">Iowa Caucuses + Trump Blocked From Primary Ballots</a> - <i>LiveNOW</i>, Orlando (2024)

<li> <a href="https://youtu.be/k_iirum-6zc?si=JAmxMaG8HhC_3m9n">Jim Jordan Ousted by House GOP as Speaker Nominee</a> - <i>LiveNOW</i>, Orlando (2023)

<li> <a href="https://youtu.be/9SoB-IeDQFU}">Kevin McCarthy ousted as House Speaker</a> - <i>KCRA 3</i>, Sacramento (2023)

<li> <a href="https://youtu.be/CfNk0dLtCxU">Laphonza Butler's Senate appointment</a> - <i>KCRA 3</i>, Sacramento (2023)

<li> <a href="https://youtu.be/m4XwpTr9qTw">Dianne Feinstein's legacy</a> - <i>LiveNOW</i>, Orlando (2023)

<li> <a href="https://youtu.be/h68df3G19Gs">October 2023 Government Shutdown Showdown</a> - <i>LiveNOW</i>, Orlando (2023)

<li> <a href="https://youtu.be/IHJRVF61cSM">Potential Replacements for Dianne Feinstein</a> - <i>KCRA 3</i>, Sacramento (2023)

<li> <a href="https://youtu.be/N357S67QSAQ">Dianne Feinstein's legacy</a> - <i>Spectrum News</i>, Los Angeles (2023)

<li> <a href="https://youtu.be/QDpy_KMqxQg?si=n54H0CPQGT_NLtpg">August 2023 Republican Debate</a> - <i>LiveNOW</i>, Orlando (2023)

<li> <a href="https://youtu.be/CyyDZMiYRwI">Trump, calls for impeachment of Biden, the USNWT, and Ohio Ballot Issue 1</a> - <i>Spectrum News</i>, Los Angeles (2023)

<li> <a href="https://youtu.be/K2h0h5vAGpw">Trump indictment developments</a> - <i>Spectrum News</i>, Los Angeles (2023)


<li> <a href="https://youtu.be/ugTjR73mJIQ">May 2023 political news</a> - <i>LiveNOW</i>, Orlando (2023)


<li> <a href="https://youtu.be/vvzwKxlED5w">Biden's Campaign Launch</a> - <i>Spectrum News</i>, Los Angeles (2023)

<li> <a href="https://youtu.be/8qyFfoUxb5o">Dianne Feinstein's Senate absence</a> - <i>LiveNOW</i>, Orlando (2023)


<li> <a href="https://youtu.be/_NTMV1Jfl8M">Dianne Feinstein's Senate absence</a> - <i>Spectrum News</i>, Los Angeles (2023)


<li> <a href="https://youtu.be/5HY4p4Kt2LU">the Trump indictment</a> - <i>LiveNOW</i>, Orlando (2023)


<li> <a href="https://www.kcra.com/article/fact-checking-proposition-27-california-sports-betting/40645691">Fact-checking Proposition 27: Experts weigh in on California's in-person sports betting measure</a> - <i>KCRA 3</i>, Sacramento (2022)




<li> <a href="https://www.kcra.com/article/fact-checking-proposition-26-californias-sports-betting/40658573">Fact-checking Proposition 26: Experts weigh in on California's in-person sports betting measure</a> - <i>KCRA 3</i>, Sacramento (2022)






<li> <a href="https://www.abc10.com/article/news/politics/kiley-jones-congressional-district-3-endorsement/103-cbdc2a46-13e7-42e1-9b63-4a14b3a5c38a">'Complete and Total Endorsement' | California congressional race intensifies as Trump backs Kiley</a> - <i>ABC 10</i>, Sacramento (2022)






<li> <a href="https://www.kcra.com/article/how-the-recall-election-called-ballots-left-to-count/37627604">How was the recall election called by news organizations, with millions of ballots left to count?</a> - <i>KCRA 3</i>, Sacramento (2021)








<li> <a href="https://fox40.com/morning/political-analyst-discusses-recall-election-as-sept-14-approaches/">Political analyst discusses recall election as Sept. 14 approaches.</a> - <i>FOX 40</i>, Sacramento (2021)




<li> <a href="https://youtu.be/Fel4EloMYb8">California's official recall list is posted. Here's what to expect.</a> - <i>ABC 10</i>, Sacramento (2021)




<li> <a href="https://fox40.com/morning/political-science-lecturer-discusses-impact-of-recall-election-ballot-case/">Political science lecturer discusses impact of recall election ballot case</a> - <i>FOX 40</i>, Sacramento (2021)



<li> <a href="https://sacramento.cbslocal.com/2021/06/11/taxpayers-cost-recall-newsom-officials-voters/">Is It Worth It? Taxpayers, Officials Weigh In On Cost Of Recall Election</a> - <i>CBS 13</i>, Sacramento (2021)



<li> <a href="https://www.abc10.com/article/news/health/coronavirus/newsom-covid-19-state-emergency-order/103-df8261d3-59b0-43a9-80ff-d973c9114978">Gov. Newsom won't lift COVID-19 state of emergency order, here's what that means</a> - <i>ABC 10</i>, Sacramento (2021)



<li> <a href="https://www.kcra.com/article/california-leaving-whos-moving-in/36358172">Here's who's leaving California and who's moving in</a> - <i>KCRA 3</i>, Sacramento (2021)



<li> <a href="https://www.abc10.com/article/news/politics/newsom-recall-cost-california-governor/103-2f285ae0-3eda-4d43-b4f6-48e83ac43c70">This is how much it may cost to recall Governor Newsom</a> - <i>ABC 10</i>, Sacramento (2021)



<li> <a href="https://fox40.com/news/california-connection/california-losing-congressional-seat-for-first-time/">California losing congressional seat for first time</a> - <i>FOX 40</i>, Sacramento (2021)



<li> <a href="https://fox40.com/morning/uc-davis-lecturer-discusses-newsom-recall-efforts/">UC Davis lecturer discusses Newsom recall efforts</a> - <i>FOX 40</i>, Sacramento (2021)




<li> <a href="https://fox40.com/news/california-connection/whats-next-in-newsom-recall-effort/">What’s next in Newsom recall effort</a> - <i>FOX 40</i>, Sacramento (2021)



<li> <a href="https://www.kcra.com/article/whats-next-gavin-newsom-recall-efforts/35774037">What’s next for Newsom recall efforts as signatures increase</a> - <i>KCRA 3</i>, Sacramento (2021)



<li> <a href="https://fox40.com/morning/interview-uc-davis-lecturer-discusses-effort-to-recall-gov-newsom/">Interview: UC Davis lecturer discusses effort to recall Gov. Newsom</a> - <i>FOX 40</i>, Sacramento (2021)




<li> <a href="https://www.kcra.com/article/polls-show-gov-gavin-newsoms-approval-rating-slipping/35435141">Polls show Gov. Gavin Newsom’s approval rating is slipping</a> - <i>KCRA 3</i>, Sacramento (2021)




 <li> <a href="https://www.cbs8.com/article/news/politics/will-newsom-face-recall/103-bd147f68-3eb7-405f-9141-1779222752b1?fbclid=IwAR2zeT22NE_MKyavAA3d1Afq-d9JVTUKjlxYYKByMGUPKRaZp4xfWgO11Us">Will Newsom face recall election? It's a 'coin flip'</a> - <i>CBS 8</i>, San Diego (2021)




 <li> <a href="https://sacramento.cbslocal.com/2020/12/08/election-debate-is-the-electoral-college-the-best-way-to-pick-a-president/">Election Debate: Is The Electoral College The Best Way To Pick A President?</a> - <i>CBS 13 News</i>, Sacramento (2020)




 <li> <a href="https://www.abc10.com/article/news/politics/as-election-season-heats-up-an-increase-in-campaign-related-theft-vandalism-seen-across-northern-california/103-d7a9ca98-6a01-437b-a81e-4c4596f0b1c1">As election season heats up, campaign-related theft, vandalism seen across Northern California</a> - <i>ABC 10 News</i>, Sacramento (2020)



 <li> <a href="https://www.abc10.com/article/news/health/coronavirus/what-the-presidents-health-could-mean-for-the-campaign-election-and-misinformation/103-b437506e-184d-422b-9a31-d5f495298f07">What the President's health could mean for the campaign, election, and misinformation</a> - <i>ABC 10 News</i>, Sacramento (2020)
 


 <li> <a href="https://tinyurl.com/y4xe3hke">Why is the California primary so important this year?</a> - <i>ABC 10 News</i>, Sacramento (2020)


</ol>
<br>

# Newspaper, Magazine, and Online News Interviews

<ol>

 <li> <a href="https://rollcall.com/2023/04/11/house-democratic-super-pac-putting-35-million-into-california/">House Democratic super PAC putting $35 million into California</a> - <i> Roll Call</i> (2023)

 <li> <a href="https://www.thecentersquare.com/california/if-props-26-27-fail-whats-the-future-of-sports-betting-in-california/article_2b2c3290-5aec-11ed-a218-fb431f5367d2.html/">If Props 26 & 27 fail, what's the future of sports betting in California?</a> - <i>The Center Square</i> (2022)

 <li> <a href="https://www.playusa.com/casino-workers-give-15-million-to-gop-candidates/">Betting On Red: Casino Execs, Workers Give $15 Million To GOP Candidates</a> - <i>Play USA</i> (2022)

 <li> <a href="https://www.pressenterprise.com/2022/10/13/confused-about-california-props-26-and-27-heres-what-each-would-do/">Confused about California Props. 26 and 27? Here’s what each would do</a> - <i>The Press-Enterprise</i> (2022)

 <li> <a href="https://www.sfgate.com/gavin-newsom-recall/article/Trump-Gavin-Newsom-mailer-Republican-ads-voting-16408553.php">Guess whose face is all over Gavin Newsom's anti-recall mailer</a> - <i>SFGATE</i> (2021)

 <li> <a href="https://californiaglobe.com/section-2/newsom-recall-team-attempting-to-nationalize-campaign-and-blame-trump/">Newsom Recall Team Attempting to Nationalize Campaign and Blame Trump</a> - <i>California Globe</i> (2021)

 <li> <a href="https://www.sfgate.com/gavin-newsom-recall/article/Gavin-Newsom-recall-ad-Republicans-candidate-Calif-16370247.php">Gavin Newsom's anti-recall ads are everywhere, but don't seem to be helping</a> - <i>SFGATE</i> (2021)
 
 <li> <a href="https://www.sfgate.com/gavin-newsom-recall/article/Gavin-Newsom-recall-candidates-who-ballot-Democrat-16342862.php">The biggest aspect of the Gavin Newsom recall no one's talking about</a> - <i>SFGATE</i> (2021)

 <li> <a href="https://www.sfgate.com/politics/article/Gavin-Newsom-recall-mask-mandate-CDC-June-15-COVID-16183415.php">How heavily did recall politics weigh on Gavin Newsom's mask decision?</a> - <i>SFGATE</i> (2021)

 <li> <a href="https://www.sfgate.com/politics/article/2021-05-Gavin-Newsom-recall-costs-who-pays-expense-16160429.php">The Gavin Newsom recall could cost $400 million. Who's paying for that?</a> - <i>SFGATE</i> (2021)

 <li> <a href="https://theaggie.org/2021/01/15/uc-davis-professors-discuss-the-future-of-republican-politics">UC Davis professors discuss the future of Republican politics</a> - <i>The California Aggie</i> (2021)

 <li> <a href="https://www.sacbee.com/article247950105.html">‘We have to do better’: California Democrats say COVID pandemic highlighted their failures</a> - <i>The Sacramento Bee</i> (2021)

 <li> <a href="https://tinyurl.com/y5e93zpu">Voting center locations announced in Yolo County, following safety guidelines</a> - <i>The California Aggie</i> (2020)

<li> <a href="https://www.nytimes.com/2019/03/20/opinion/beto-presidential-campaign.html">Is Betomania Real or Phony?</a> - <i>The New York Times</i> (2019)

</ol>
<br>

# Radio & Podcast Interviews


<ol>

<li> <figure>
    <figcaption><a href="https://www.kalw.org/show/your-call/2022-10-27/ca-propositions-26-27-the-most-expensive-in-us-history-could-change-the-future-of-sports-gambling">CA Propositions 26 & 27, the most expensive in US history, could change the future of sports gambling</a> - <i>KALW</i>, Bay Area (2022)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KALW_26_27.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>


<li> <figure>
    <figcaption><a href="https://www.kcrw.com/news/shows/press-play-with-madeleine-brand/sports-betting-trans-kids-sterilization-holocaust-baking/prop-26-27">Could CA become one of the biggest sports betting markets in the world?</a> - <i>KCRW</i>, Santa Monica (2022)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KCRW_26_27.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>




<li> <figure>
    <figcaption><a href="https://omny.fm/shows/kcbsam-on-demand/expert-clarifies-difference-between-ca-proposition">Expert clarifies difference between CA Propositions 26 and 27 </a> - <i>KCBS Radio</i>, San Francisco (2022)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KCBS_26_27.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>




<li> <figure>
    <figcaption><a href="https://www.kqed.org/forum/2010101885507/statewide-election-special-the-2021-california-gubernatorial-recall-2">Statewide Election Special: The 2021 California Gubernatorial Recall</a> - <i>Forum (KQED-FM)</i>, San Francisco (2021)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/Forum_09_15_2021.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>


<li> <figure>
    <figcaption>California Recall Report, August 31st 2021 - <i>93.1 KFBK</i>, Sacramento (2021)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KFBK_08_31_2021.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>

<li> <figure>
    <figcaption>Recall ballots will be mailed to voters starting mid-August - <i>KCBS AM</i>, San Francisco (2021)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KCBS.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>

<br>

<li> <figure>
    <figcaption>California Recall Report, May 25th 2021 - <i>93.1 KFBK</i>, Sacramento (2021)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/KFBK.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>


<br>

<li> <a href="https://natcompodcast.podbean.com/e/bonus-communicating-about-the-role-of-race-and-social-change-in-politics/">Communicating about the Role of Race and Social Change in Politics</a> - <i>Communication Matters</i>, the National Communication Association podcast (2020)
   <br style="line-height:0px;" />
   
<iframe width="640" height="155" iframe title="BONUS: Communicating about the Role of Race and Social Change in Politics" src="https://www.podbean.com/media/player/fguap-eeb9c8?from=usersite&vjs=1&skin=1&fonts=Helvetica&auto=0&download=1" scrolling="no"></iframe></li>
<br>






<li> <figure>
    <figcaption><a href="http://www.bluedevilhub.com/2020/10/05/first-2020-presidential-debate-locals-react/">First 2020 Presidential Debate: Locals React</a> - <i>The News Cycle</i>, a Davis High School podcast (2020)</figcaption>
    <audio
        controls
        src="https://github.com/isaacdhale/personal_site/raw/master/audio/News_Cycle.mp3">
            Your browser does not support the
            <code>audio</code> element.
    </audio>
</figure>



</ol>
<br>

